### ISSUE TITLE
Entering decimal number for order in checklist causes error

### ISSUE THREAD

**Issue by bgillock** [wasabee-project/Wasabee-IITC#354]
1. Enter a decimal number (eg. 35.1) in the order field of a row in the checklist.
2. Upload project

Get "Update Failed:: json:..." 

<img width="664" alt="Screen Shot 2022-04-21 at 8 37 03 AM" src="https://user-images.githubusercontent.com/17684691/164471953-35d3eafd-326d-401a-a276-1110027ea95c.png">

I believe this can be fixed very easily at data entry time, which I would be glad to do. 

Or a more elaborate fix, and one that adds functionality, is to support decimal order numbers in the database.

**Comment by cloudkucooland** [comment]
Fix it in the client. We aren't changing the database schema until we work up the v2 JSON format.

**Comment by SebastienForay** [comment]
@crystalwizard Because when you ordered all the checklist and then you want to add an intermediate task, you have to reorder all (from the plugin). Not everyone is aware that WebUI is better for handling this case. So the decimal makes sense here to add something easily between two tasks

**Comment by crystalwizard** [comment]
Is adding the ability to use decimals better than just having all the tasks after the one you're inserting automatically increment themselves by 1?

**Comment by cloudkucooland** [comment]
It's a fine concept. One that could be useful (for those unwilling to learn the superior dependency system already in place).

It would allow denotation of parallel tasks (all the 1.x at the same time by different people) or grouping of independent tasks (bob does 1.x, alice does 2.x etc)

I think the dependency system already in place covers all these (kudos to @le-jeu for the excellent work there) but it might be a bit too much for non-power-users. These are things to discuss when we start thinking through what v2 will do differently.

I'm just amazed at the complexity of some of the operations that people are doing. Wasabee has made even more complex ops possible. But... now people want to go to a level I'd never envisioned. Which is great, but will require a deep re-think of how best to do it.

I don't want to build a tool that is too complex for "normal" users.
I don't want to build a tool that is too limiting for "power" users.

It might well be that such a thing is impossible and two different Wasabee-IITCs are necessary. One "core" version which covers the basics and a "pro" version which has the extended features.

What we have now is probably too much for "normal" users and too little for "power" users... but just about right for what the developers want.

**Comment by crystalwizard** [comment]
Instead of two tools, perhaps an option that enables the more advanced stuff for power users - with the default being the basic tools/configuration when first installed?

**Comment by le-jeu** [comment]
Having two client is off topic and deserve its own issue.

Back on topic, decimal point numbering is not a goal, it's a way to solve an reordering problem. 
One could want to use dotted notation, or letters etc.
The current data scheme uses integers, that can cover _any_ throwing order.

If the issue is to move a task between others with consecutive numbers, we need an interactive way to move a task between other tasks (whatever their order number), and then, the order will be reflected in the numbering. 
The numbering is just a way to display the final order

Current backend allows to store info about the dependencies between tasks, basically which tasks should be done after/before another. Giving this information, we can infer an order (thus a numbering, but we want an order right?).
WebUI gives a taste of what can be done on this aspect but lacks feedback to make things usable for common users.
